
const routes = [
    {
      path:'/',
      redirect:"/index"
    },
    {
      path:'/index',
      component:()=>import("../views/index/index.vue"),
      redirect:'/index/home',
      meta:{
        requiresAuth:false,
      },
      children:[
        {
          path:"home",
          component:()=>import("../views/index/home/home.vue"),
          meta:{
            requiresAuth:false,
          },
        },
        {
          path:"classify",
          component:()=>import("../views/index/classify/classify.vue"),
          meta:{
            requiresAuth:false,
          },
        },
        {
          path:"cart",
          component:()=>import("../views/index/cart/cart.vue"),
          meta:{
            requiresAuth:true,
          },
        },
        {
          path:"my",
          component:()=>import("../views/index/my/my.vue"),
          meta:{
            requiresAuth:true,
          },
        }
      ]
    },
    {
      path:'/detail',
      component:()=>import("../views/detail/detail.vue"),
      meta:{
        requiresAuth:false,
      }
    },
    {
      path:'/login',
      component:()=>import("../views/login/login.vue"),
      meta:{
        requiresAuth:false,
      }
    },
    {
      path:'/registy',
      component:()=>import("../views/registy/registy.vue"),
      meta:{
        requiresAuth:false,
      },
    }
  ] 
export default routes  